source: doc
destination: ..\gh-pages
timezone: America/Vancouver

baseurl: /SpaceBattleArena
url: http://mikeware.github.io/SpaceBattleArena

githuburl: https://www.github.com/Mikeware/SpaceBattleArena
releasepath: https://github.com/Mikeware/SpaceBattleArena/releases/download/v1.2.0.1125

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
